### ISSUE TITLE
Cell disappear

### ISSUE THREAD

**Issue by Aixtuz** [moayes/UDo#3]
Long press and Immediate release, the cell will disappear.

**Comment by Aixtuz** [comment]
Sorry, my mistake. It's hidden, not disappear.
Long press and Immediate release(very fast), the cell will be hidden. But long press again, it can be redisplay.

**Comment by Aixtuz** [comment]
# As you wish :  
- case UIGestureRecognizerStateBegan:  cell.hidden = YES;
- default: cell.hidden = NO; (UIGestureRecognizerStateEnded)

# In fact:
- case UIGestureRecognizerStateBegan:  cell.hidden = YES; (delay 0.25 for animation)
- default: cell.hidden = NO;
- therefore, **cell.hidden will be : NO ----(0.25s)---- YES;**

# Solution
- Method 1: 
**case UIGestureRecognizerStateBegan:**
```
[UIView animateWithDuration:0.25 animations:^{
    ...
    cell.hidden = YES;
}];
```
- Method 2: 
**default:**
```
[UIView animateWithDuration:0.25 animations:^{
    ....
} completion:^(BOOL finished) {
    cell.hidden = NO;
    ...
}];
```

# I will pull request，hope merged;

-----

# 问题
- 长按 Cell 进入拖动状态，0.25s 内松手，cell 会消失；

#原因
- 作者希望 0.25s 动画后 隐藏 cell，手势结束时恢复显示；
- 松手太快导致，手势结束 cell 显示的代码执行完毕，才执行延迟 0.25s 的隐藏代码；

# 解决
- 方法1: 将隐藏 cell 从动画完成后的 Block 中移到 动画 Block 中（提前隐藏）；
- 方法2: 将 default 中的显示cell，移到之后 0.25s 动画执行完毕的 Block 中（延迟显示）；
- 由于执行显隐时间不同, 方法1和方法2 会分别在长按或松手时明显闪烁一下, 可根据爱好选择.
- 具体代码见英文部分；

**Comment by yu0winter** [comment]
you can change code in this way:
      cell.hidden = NO;
      cell.alpha = 0.0;
      
===>>
        cell.hidden = NO;
        cell.alpha = 0.0;

**Comment by yu0winter** [comment]
加两行代码，就可以解决了。

UDo/RWTableViewController.m
@@ -182,6 +180,8 @@
        sourceIndexPath = nil;
        [snapshot removeFromSuperview];
        snapshot = nil;
  +      cell.hidden = NO;
  +      cell.alpha = 0.0;
        
      }];
